// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.far.eventmanagerpanels.domain;

import com.far.eventmanagerpanels.domain.Evento;
import com.far.eventmanagerpanels.domain.EventoDataOnDemand;
import com.far.eventmanagerpanels.domain.EventoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EventoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EventoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EventoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EventoIntegrationTest: @Transactional;
    
    @Autowired
    private EventoDataOnDemand EventoIntegrationTest.dod;
    
    @Test
    public void EventoIntegrationTest.testCountEventoes() {
        Assert.assertNotNull("Data on demand for 'Evento' failed to initialize correctly", dod.getRandomEvento());
        long count = Evento.countEventoes();
        Assert.assertTrue("Counter for 'Evento' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EventoIntegrationTest.testFindEvento() {
        Evento obj = dod.getRandomEvento();
        Assert.assertNotNull("Data on demand for 'Evento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Evento' failed to provide an identifier", id);
        obj = Evento.findEvento(id);
        Assert.assertNotNull("Find method for 'Evento' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Evento' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EventoIntegrationTest.testFindAllEventoes() {
        Assert.assertNotNull("Data on demand for 'Evento' failed to initialize correctly", dod.getRandomEvento());
        long count = Evento.countEventoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Evento', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Evento> result = Evento.findAllEventoes();
        Assert.assertNotNull("Find all method for 'Evento' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Evento' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EventoIntegrationTest.testFindEventoEntries() {
        Assert.assertNotNull("Data on demand for 'Evento' failed to initialize correctly", dod.getRandomEvento());
        long count = Evento.countEventoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Evento> result = Evento.findEventoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Evento' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Evento' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EventoIntegrationTest.testFlush() {
        Evento obj = dod.getRandomEvento();
        Assert.assertNotNull("Data on demand for 'Evento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Evento' failed to provide an identifier", id);
        obj = Evento.findEvento(id);
        Assert.assertNotNull("Find method for 'Evento' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEvento(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Evento' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EventoIntegrationTest.testMergeUpdate() {
        Evento obj = dod.getRandomEvento();
        Assert.assertNotNull("Data on demand for 'Evento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Evento' failed to provide an identifier", id);
        obj = Evento.findEvento(id);
        boolean modified =  dod.modifyEvento(obj);
        Integer currentVersion = obj.getVersion();
        Evento merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Evento' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EventoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Evento' failed to initialize correctly", dod.getRandomEvento());
        Evento obj = dod.getNewTransientEvento(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Evento' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Evento' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Evento' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EventoIntegrationTest.testRemove() {
        Evento obj = dod.getRandomEvento();
        Assert.assertNotNull("Data on demand for 'Evento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Evento' failed to provide an identifier", id);
        obj = Evento.findEvento(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Evento' with identifier '" + id + "'", Evento.findEvento(id));
    }
    
}
