// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.far.eventmanagerpanels.domain;

import com.far.eventmanagerpanels.domain.Painel;
import com.far.eventmanagerpanels.domain.PainelDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PainelDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PainelDataOnDemand: @Component;
    
    private Random PainelDataOnDemand.rnd = new SecureRandom();
    
    private List<Painel> PainelDataOnDemand.data;
    
    public Painel PainelDataOnDemand.getNewTransientPainel(int index) {
        Painel obj = new Painel();
        setCodigo(obj, index);
        setNome(obj, index);
        return obj;
    }
    
    public void PainelDataOnDemand.setCodigo(Painel obj, int index) {
        String codigo = "codigo_" + index;
        obj.setCodigo(codigo);
    }
    
    public void PainelDataOnDemand.setNome(Painel obj, int index) {
        String nome = "nome_" + index;
        obj.setNome(nome);
    }
    
    public Painel PainelDataOnDemand.getSpecificPainel(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Painel obj = data.get(index);
        Long id = obj.getId();
        return Painel.findPainel(id);
    }
    
    public Painel PainelDataOnDemand.getRandomPainel() {
        init();
        Painel obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Painel.findPainel(id);
    }
    
    public boolean PainelDataOnDemand.modifyPainel(Painel obj) {
        return false;
    }
    
    public void PainelDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Painel.findPainelEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Painel' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Painel>();
        for (int i = 0; i < 10; i++) {
            Painel obj = getNewTransientPainel(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
