// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.far.eventmanagerpanels.domain;

import com.far.eventmanagerpanels.domain.Painel;
import com.far.eventmanagerpanels.domain.PainelDataOnDemand;
import com.far.eventmanagerpanels.domain.PainelIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PainelIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PainelIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PainelIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PainelIntegrationTest: @Transactional;
    
    @Autowired
    private PainelDataOnDemand PainelIntegrationTest.dod;
    
    @Test
    public void PainelIntegrationTest.testCountPainels() {
        Assert.assertNotNull("Data on demand for 'Painel' failed to initialize correctly", dod.getRandomPainel());
        long count = Painel.countPainels();
        Assert.assertTrue("Counter for 'Painel' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PainelIntegrationTest.testFindPainel() {
        Painel obj = dod.getRandomPainel();
        Assert.assertNotNull("Data on demand for 'Painel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Painel' failed to provide an identifier", id);
        obj = Painel.findPainel(id);
        Assert.assertNotNull("Find method for 'Painel' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Painel' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PainelIntegrationTest.testFindAllPainels() {
        Assert.assertNotNull("Data on demand for 'Painel' failed to initialize correctly", dod.getRandomPainel());
        long count = Painel.countPainels();
        Assert.assertTrue("Too expensive to perform a find all test for 'Painel', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Painel> result = Painel.findAllPainels();
        Assert.assertNotNull("Find all method for 'Painel' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Painel' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PainelIntegrationTest.testFindPainelEntries() {
        Assert.assertNotNull("Data on demand for 'Painel' failed to initialize correctly", dod.getRandomPainel());
        long count = Painel.countPainels();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Painel> result = Painel.findPainelEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Painel' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Painel' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PainelIntegrationTest.testFlush() {
        Painel obj = dod.getRandomPainel();
        Assert.assertNotNull("Data on demand for 'Painel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Painel' failed to provide an identifier", id);
        obj = Painel.findPainel(id);
        Assert.assertNotNull("Find method for 'Painel' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPainel(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Painel' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PainelIntegrationTest.testMergeUpdate() {
        Painel obj = dod.getRandomPainel();
        Assert.assertNotNull("Data on demand for 'Painel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Painel' failed to provide an identifier", id);
        obj = Painel.findPainel(id);
        boolean modified =  dod.modifyPainel(obj);
        Integer currentVersion = obj.getVersion();
        Painel merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Painel' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PainelIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Painel' failed to initialize correctly", dod.getRandomPainel());
        Painel obj = dod.getNewTransientPainel(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Painel' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Painel' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Painel' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PainelIntegrationTest.testRemove() {
        Painel obj = dod.getRandomPainel();
        Assert.assertNotNull("Data on demand for 'Painel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Painel' failed to provide an identifier", id);
        obj = Painel.findPainel(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Painel' with identifier '" + id + "'", Painel.findPainel(id));
    }
    
}
