// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.far.eventmanagerpanels.domain;

import com.far.eventmanagerpanels.domain.TipoEvento;
import com.far.eventmanagerpanels.domain.TipoEventoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect TipoEventoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TipoEventoDataOnDemand: @Component;
    
    private Random TipoEventoDataOnDemand.rnd = new SecureRandom();
    
    private List<TipoEvento> TipoEventoDataOnDemand.data;
    
    public TipoEvento TipoEventoDataOnDemand.getNewTransientTipoEvento(int index) {
        TipoEvento obj = new TipoEvento();
        setNome(obj, index);
        return obj;
    }
    
    public void TipoEventoDataOnDemand.setNome(TipoEvento obj, int index) {
        String nome = "nome_" + index;
        obj.setNome(nome);
    }
    
    public TipoEvento TipoEventoDataOnDemand.getSpecificTipoEvento(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TipoEvento obj = data.get(index);
        Long id = obj.getId();
        return TipoEvento.findTipoEvento(id);
    }
    
    public TipoEvento TipoEventoDataOnDemand.getRandomTipoEvento() {
        init();
        TipoEvento obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TipoEvento.findTipoEvento(id);
    }
    
    public boolean TipoEventoDataOnDemand.modifyTipoEvento(TipoEvento obj) {
        return false;
    }
    
    public void TipoEventoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TipoEvento.findTipoEventoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TipoEvento' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TipoEvento>();
        for (int i = 0; i < 10; i++) {
            TipoEvento obj = getNewTransientTipoEvento(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
