// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.far.eventmanagerpanels.domain;

import com.far.eventmanagerpanels.domain.TipoEvento;
import com.far.eventmanagerpanels.domain.TipoEventoDataOnDemand;
import com.far.eventmanagerpanels.domain.TipoEventoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TipoEventoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TipoEventoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TipoEventoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TipoEventoIntegrationTest: @Transactional;
    
    @Autowired
    private TipoEventoDataOnDemand TipoEventoIntegrationTest.dod;
    
    @Test
    public void TipoEventoIntegrationTest.testCountTipoEventoes() {
        Assert.assertNotNull("Data on demand for 'TipoEvento' failed to initialize correctly", dod.getRandomTipoEvento());
        long count = TipoEvento.countTipoEventoes();
        Assert.assertTrue("Counter for 'TipoEvento' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TipoEventoIntegrationTest.testFindTipoEvento() {
        TipoEvento obj = dod.getRandomTipoEvento();
        Assert.assertNotNull("Data on demand for 'TipoEvento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoEvento' failed to provide an identifier", id);
        obj = TipoEvento.findTipoEvento(id);
        Assert.assertNotNull("Find method for 'TipoEvento' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TipoEvento' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TipoEventoIntegrationTest.testFindAllTipoEventoes() {
        Assert.assertNotNull("Data on demand for 'TipoEvento' failed to initialize correctly", dod.getRandomTipoEvento());
        long count = TipoEvento.countTipoEventoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'TipoEvento', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TipoEvento> result = TipoEvento.findAllTipoEventoes();
        Assert.assertNotNull("Find all method for 'TipoEvento' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TipoEvento' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TipoEventoIntegrationTest.testFindTipoEventoEntries() {
        Assert.assertNotNull("Data on demand for 'TipoEvento' failed to initialize correctly", dod.getRandomTipoEvento());
        long count = TipoEvento.countTipoEventoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TipoEvento> result = TipoEvento.findTipoEventoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TipoEvento' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TipoEvento' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TipoEventoIntegrationTest.testFlush() {
        TipoEvento obj = dod.getRandomTipoEvento();
        Assert.assertNotNull("Data on demand for 'TipoEvento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoEvento' failed to provide an identifier", id);
        obj = TipoEvento.findTipoEvento(id);
        Assert.assertNotNull("Find method for 'TipoEvento' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTipoEvento(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TipoEvento' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TipoEventoIntegrationTest.testMergeUpdate() {
        TipoEvento obj = dod.getRandomTipoEvento();
        Assert.assertNotNull("Data on demand for 'TipoEvento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoEvento' failed to provide an identifier", id);
        obj = TipoEvento.findTipoEvento(id);
        boolean modified =  dod.modifyTipoEvento(obj);
        Integer currentVersion = obj.getVersion();
        TipoEvento merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TipoEvento' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TipoEventoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TipoEvento' failed to initialize correctly", dod.getRandomTipoEvento());
        TipoEvento obj = dod.getNewTransientTipoEvento(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TipoEvento' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TipoEvento' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TipoEvento' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TipoEventoIntegrationTest.testRemove() {
        TipoEvento obj = dod.getRandomTipoEvento();
        Assert.assertNotNull("Data on demand for 'TipoEvento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoEvento' failed to provide an identifier", id);
        obj = TipoEvento.findTipoEvento(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TipoEvento' with identifier '" + id + "'", TipoEvento.findTipoEvento(id));
    }
    
}
