// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.far.eventmanagerpanels.domain;

import com.far.eventmanagerpanels.domain.TipoEventoIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TipoEventoIntegrationTest_Roo_Configurable {
    
    declare @type: TipoEventoIntegrationTest: @Configurable;
    
}
