// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.far.eventmanagerpanels.domain;

import com.far.eventmanagerpanels.domain.TipoEvento;

privileged aspect TipoEvento_Roo_JavaBean {
    
    public String TipoEvento.getNome() {
        return this.nome;
    }
    
    public void TipoEvento.setNome(String nome) {
        this.nome = nome;
    }
    
}
